
- name: Unarchive trufflehog tarball
  ansible.builtin.unarchive:
    src: https://github.com/trufflesecurity/trufflehog/releases/download/v3.0.5/trufflehog_3.0.5_linux_amd64.tar.gz
    dest: "{{ playbook_dir }}"
    remote_src: true

      
- name: Scan "{{ org }}" Github Org
  ansible.builtin.command: "./{{ playbook_dir }}/trufflehog github --org={{ org }}"
  when: org is defined
  register: org_scan.stdout


- name: Scan "{{ repo }}" Github Repo
  ansible.builtin.command: "./{{ playbook_dir }}/trufflehog github --repo={{ repo }}"
  when: repo is defined
  register: repo_scan.stdout

- name: Create Results dir
  ansible.builtin.file:
    path: /tmp/trufflehog
    state: directory
    mode: '0755'

- name: Create Org "{{ org }}" results file
  copy:
    dest: "/tmp/trufflehog/{{ org }}/{{ org }}-results.txt"
    content: "{{ org_scan.stdout }}"
  when:  org_scan.stdout exists

  - name: Create Repo "{{ repo }}" results file
  copy:
    dest: "/tmp/trufflehog/{{ repo }}/{{ repo }}-results.txt"
    content: "{{ repo_scan.stdout }}"
  when:  repo_scan.stdout exists